// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineShopWebApp.Data;

#nullable disable

namespace OnlineShopWebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineShopWebApp.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1999m,
                            Description = "Elden Ring — это захватывающая action-RPG...",
                            ImagePath = "/images/Elden_Ring_Logo.jpg",
                            Name = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 1299m,
                            Description = "Cyberpunk 2077 — это ролевая игра...",
                            ImagePath = "/images/Cyberpunk_2077_Logo.jpg",
                            Name = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1999m,
                            Description = "Baldur's Gate 3 — это эпическая ролевая игра...",
                            ImagePath = "/images/Baldurs_Gate_3_Logo.jpg",
                            Name = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 1499m,
                            Description = "Path of Exile 2 — это продолжение культовой action-RPG...",
                            ImagePath = "/images/Path_Of_Exile_2_Logo.jpg",
                            Name = "Path of Exile 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
